# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_menuUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import pymongo
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QIntValidator
from PyQt5.QtWidgets import QFileDialog
import base64
import datacollect
import dns

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(689, 449)
        Dialog.setStyleSheet("background-color: rgb(255, 198, 98);")
        self.confirm_but = QtWidgets.QPushButton(Dialog)
        self.confirm_but.setGeometry(QtCore.QRect(480, 380, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.confirm_but.setFont(font)
        self.confirm_but.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color:rgb(0, 206, 165);\n"
"border:none")
        self.confirm_but.setObjectName("confirm_but")
        self.img_frame = QtWidgets.QFrame(Dialog)
        self.img_frame.setGeometry(QtCore.QRect(10, 40, 211, 261))
        self.img_frame.setStyleSheet("background-color: rgb(206, 205, 205);")
        self.img_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.img_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.img_frame.setObjectName("img_frame")
        self.img_frame_2 = QtWidgets.QLabel(self.img_frame)
        self.img_frame_2.setGeometry(QtCore.QRect(0, 0, 211, 261))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.img_frame_2.setFont(font)
        self.img_frame_2.setStyleSheet("color:white\n"
"")
        self.img_frame_2.setText("")
        self.img_frame_2.setObjectName("img_frame_2")
        self.showimage = QtWidgets.QLabel(self.img_frame)
        self.showimage.setGeometry(QtCore.QRect(0, 0, 211, 261))
        self.showimage.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.showimage.setText("")
        self.showimage.setObjectName("showimage")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(250, 40, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(260, 230, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(260, 100, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(260, 290, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(540, 230, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.name = QtWidgets.QTextEdit(Dialog)
        self.name.setGeometry(QtCore.QRect(400, 50, 261, 31))
        self.name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.name.setObjectName("name")
        self.recipe = QtWidgets.QTextEdit(Dialog)
        self.recipe.setGeometry(QtCore.QRect(400, 110, 261, 101))
        self.recipe.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.recipe.setObjectName("recipe")
        self.price = QtWidgets.QLineEdit(Dialog)
        self.price.setGeometry(QtCore.QRect(400, 240, 101, 31))
        self.price.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.onlyInt = QIntValidator()
        self.price.setValidator(self.onlyInt)
        self.price.setObjectName("price")
        self.point = QtWidgets.QLineEdit(Dialog)
        self.point.setGeometry(QtCore.QRect(400, 300, 101, 31))
        self.point.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.onlyInt = QIntValidator()
        self.point.setValidator(self.onlyInt)
        self.point.setObjectName("point")
        self.add_image_but = QtWidgets.QPushButton(Dialog)
        self.add_image_but.setGeometry(QtCore.QRect(10, 310, 211, 23))
        self.add_image_but.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color: rgb(162, 162, 162);\n"
"border:none")
        self.add_image_but.setObjectName("add_image_but")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.confirm_but.clicked.connect(self.addmenu)
        self.add_image_but.clicked.connect(self.browsefiles)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.confirm_but.setText(_translate("Dialog", "Confirm"))
        self.label.setText(_translate("Dialog", " Name :"))
        self.label_3.setText(_translate("Dialog", "price : "))
        self.label_2.setText(_translate("Dialog", "recipe :"))
        self.label_4.setText(_translate("Dialog", "point :"))
        self.label_5.setText(_translate("Dialog", "Baht"))
        self.add_image_but.setText(_translate("Dialog", "Add Image"))


    def browsefiles(self):
        #fname=QFileDialog.getOpenFileName(self, 'Open file', 'C:\Destop', 'Images (*.png, *.xmp *.jpg)')
        fname = QFileDialog.getOpenFileName()
        print(fname[0])
        pixmap = QPixmap(fname[0])
        pixmapre = pixmap.scaled(211, 261)
        self.showimage.setPixmap(pixmapre)
        filepath = fname[0]
        with open(filepath, "rb") as img_file:
            mystring = base64.b64encode(img_file.read())
            datacollect.menu_img = mystring


    def addmenu(self):

        name = self.name.toPlainText()
        recipe = self.recipe.toPlainText()
        price = self.price.text()
        point = self.point.text()

        check = True

        if len(name) == 0 or len(recipe) == 0 or len(price) == 0 or len(point) == 0 or len(datacollect.menu_img) == 0:
            check = False
            datacollect.show_popuperror('plz fill in the infomation')
        else:
            cloudDatabase = "mongodb+srv://Wan:Hktdtn234@cluster0.pofzb.mongodb.net/lets_read?retryWrites=true&w=majority"
            with pymongo.MongoClient(cloudDatabase) as conn:
                db = conn.get_database('Milk_Tea')

                data = {'menu_name': name, 'recipe': recipe, 'price': int(price), 'point': int(point),'menu_image': datacollect.menu_img}
                cursor = db.menu.find()
                for i in cursor:
                    if i['menu_name'].lower() == name.lower():
                        check = False
                        datacollect.show_popuperror('This Menu name has already been used')

                if check == True:
                    #print(data)
                    db.menu.insert_one(data)
                    datacollect.show_popupsuccess("Menu Added")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
