# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addmember.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIntValidator

import pymongo
import dns
import datacollect

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(530, 389)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_3 = QtWidgets.QFrame(Dialog)
        self.frame_3.setGeometry(QtCore.QRect(20, 10, 491, 81))
        self.frame_3.setStyleSheet("background-color: rgb(53, 53, 53);\n"
"border-width:2px;  \n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.name = QtWidgets.QLabel(self.frame_3)
        self.name.setGeometry(QtCore.QRect(100, 10, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.name.setFont(font)
        self.name.setStyleSheet("color:white;")
        self.name.setObjectName("name")
        self.confirm = QtWidgets.QPushButton(Dialog)
        self.confirm.setGeometry(QtCore.QRect(440, 350, 75, 23))
        self.confirm.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color:rgb(0, 170, 0);\n"
"border:none;")
        self.confirm.setObjectName("confirm")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 120, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 220, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tel = QtWidgets.QLineEdit(Dialog)
        self.tel.setGeometry(QtCore.QRect(180, 120, 321, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.tel.setFont(font)
        self.tel.setText("")
        self.tel.setObjectName("tel")
        self.name_2 = QtWidgets.QLineEdit(Dialog)
        self.name_2.setGeometry(QtCore.QRect(180, 230, 321, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.name_2.setFont(font)
        self.name_2.setText("")
        self.name_2.setObjectName("name_2")

        self.onlyInt = QIntValidator()
        self.tel.setValidator(self.onlyInt)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.confirm.clicked.connect(self.addmember)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.name.setText(_translate("Dialog", "Add Membership"))
        self.confirm.setText(_translate("Dialog", "confirm"))
        self.label.setText(_translate("Dialog", "Tel"))
        self.label_2.setText(_translate("Dialog", "Name"))


    def addmember(self):
        cloudDatabase = "mongodb+srv://Wan:Hktdtn234@cluster0.pofzb.mongodb.net/lets_read?retryWrites=true&w=majority"
        with pymongo.MongoClient(cloudDatabase) as conn:
            db = conn.get_database('Milk_Tea')
            name = self.name_2.text()
            Tel = self.tel.text()
            cursor = db.member.find()
            check = True

            if len(Tel) == 0 or len(name) == 0 :
                datacollect.show_popuperror('กรุณากรอกข้อมูลให้ครบ')
                check = False

            for i in cursor:
                if i['tel'] == Tel or i['name'].lower() == name.lower():
                    print(i['name'].lower())
                    check = False
                    datacollect.show_popuperror('ชื่อหรือเบอร์ถูกใช้ไปเเล้ว')
                    break


            if check == True:
                data = {'name': name, 'tel': Tel, 'points': 0}
                db.member.insert_one(data)
                datacollect.show_popupsuccess('ลงทะเบียนเรียบร้อย')



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
