# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checkout_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import datacollect
import milktea_main

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(883, 834)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(120, 30, 671, 671))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(15)
        self.formLayout.setVerticalSpacing(29)
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.name = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(32)
        self.name.setFont(font)
        self.name.setText("-")
        self.name.setObjectName("name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.name)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.point_use = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(32)
        self.point_use.setFont(font)
        self.point_use.setObjectName("point_use")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.point_use)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.point_get = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(32)
        self.point_get.setFont(font)
        self.point_get.setObjectName("point_get")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.point_get)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.Discount = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(32)
        self.Discount.setFont(font)
        self.Discount.setObjectName("Discount")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.Discount)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.Total = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(32)
        self.Total.setFont(font)
        self.Total.setObjectName("Total")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.Total)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.cash = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(27)
        self.cash.setFont(font)
        self.cash.setStyleSheet(" background-color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"")
        self.cash.setObjectName("cash")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.cash)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_15.setFont(font)
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.change = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(32)
        self.change.setFont(font)
        self.change.setObjectName("change")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.change)
        self.check_out = QtWidgets.QPushButton(Dialog)
        self.check_out.setGeometry(QtCore.QRect(660, 740, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.check_out.setFont(font)
        self.check_out.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color:white;\n"
"border-style:outset;\n"
"")
        self.check_out.setObjectName("check_out")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.setinfo()
        self.check_out.clicked.connect(self.Change)

    def setinfo(self):
        # datacollect.member = True
        if datacollect.member == True:
            self.name.setText("{}".format(datacollect.member_name))
            self.point_use.setText("{}".format(datacollect.point_get))
            self.point_get.setText("{}".format(datacollect.point))
            if datacollect.point_use == True:
                self.Discount.setText("10%")
                self.point_use.setText("{}".format(datacollect.point_get))
                self.point_get.setText("{}".format(datacollect.point))
                self.Total.setText("{:.1f} Baht".format(datacollect.final_total - ((datacollect.final_total*10)/100)))
            else:
                self.Discount.setText("-")
                self.Total.setText("{} Baht".format(datacollect.final_total))
                self.Discount.setText("-")
        else:
            self.Discount.setText("-")
            self.point_get.setText("-")
            self.point_use.setText("-")
            self.Total.setText("{} Baht".format(datacollect.final_total))


    def Change(self):
        total = self.Total.text().split(" ")
        cash = self.cash.text()
        if len(cash) == 0:
            self.change.setText("กรุณาใส่จํานวนเงิน")
        else:
            self.change.setText("{:.1f} Baht".format(int(cash)-float(total[0])))

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_6.setText(_translate("Dialog", "Member :"))

        self.label_10.setText(_translate("Dialog", "Point Get :"))
        # self.point_use.setText(_translate("Dialog", "20"))
        self.label_11.setText(_translate("Dialog", "Current Point :"))
        # self.point_get.setText(_translate("Dialog", "40"))
        self.label_4.setText(_translate("Dialog", "Discount :"))
        # self.Discount.setText(_translate("Dialog", "300"))
        self.label_7.setText(_translate("Dialog", "Total : "))
        # self.Total.setText(_translate("Dialog", "300"))
        self.label_13.setText(_translate("Dialog", "Cash : "))
        self.label_16.setText(_translate("Dialog", "Change : "))
        # self.change.setText(_translate("Dialog", "300"))
        self.check_out.setText(_translate("Dialog", "คิดเงิน"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
